_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: fbc017aa-3b56-4561-b9fb-f0700b0a787b
name: OtherName
mail: admin@example.com
slogan: 'Drupal is awesome platform'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
