_core:
  default_config_hash: l23AWlsVwlhblRhggKqahd8SBZzQDs5_GsFuCKgDItg
exclude_paths: "/contextual/*\r\n/toolbar/*\r\n/edit/*\r\n*.js\r\n*.css"
intercept_redirects: false
purge_on_cache_clear: false
active_toolbar_items:
  ajax: ajax
  blocks: blocks
  configs: configs
  database: database
  devel: devel
  events: events
  extensions: extensions
  http: http
  memory: memory
  request: request
  routing: routing
  services: services
  theme: theme
  time: time
  user: user
  views: views
  assets: '0'
  cache: '0'
  forms: '0'
  frontend: '0'
  mail: '0'
  state: '0'
  translations: '0'
query_sort: source
query_highlight: 5
ide: 'phpstorm://open?file=%f&line=%l'
ide_remote_path: ''
ide_local_path: ''
